# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: store-microservices
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "store_db"
        - name: POSTGRES_USER
          value: "store_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: store-secrets
              key: database-password
        - name: POSTGRES_MULTIPLE_DATABASES
          value: "store_identity_db,store_product_db,store_cart_db,store_order_db"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: store-microservices
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
# PostgreSQL Init Script ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: store-microservices
data:
  init-databases.sh: |
    #!/bin/bash
    set -e
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE store_identity_db;
        CREATE DATABASE store_product_db;
        CREATE DATABASE store_cart_db;
        CREATE DATABASE store_order_db;
        
        GRANT ALL PRIVILEGES ON DATABASE store_identity_db TO $POSTGRES_USER;
        GRANT ALL PRIVILEGES ON DATABASE store_product_db TO $POSTGRES_USER;
        GRANT ALL PRIVILEGES ON DATABASE store_cart_db TO $POSTGRES_USER;
        GRANT ALL PRIVILEGES ON DATABASE store_order_db TO $POSTGRES_USER;
    EOSQL
