# Template for microservice deployments
# This file serves as a template - copy and modify for each service

# Example: ProductService Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: store-microservices
  labels:
    app: product-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        tier: backend
    spec:
      containers:
      - name: product-service
        image: store/product-service:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: store-config
              key: ConnectionStrings__DefaultConnection
        - name: Redis__ConnectionString
          valueFrom:
            configMapKeyRef:
              name: store-config
              key: Redis__ConnectionString
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# Example: ProductService Service
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: store-microservices
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
