<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Store.Contracts\Store.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\Store.BuildingBlocks\Store.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Shared\Store.Shared\Store.Shared.csproj" />
    <ProjectReference Include="..\..\Services\IdentityService\Store.IdentityService.csproj" />
    <ProjectReference Include="..\..\Services\ProductService\Store.ProductService.csproj" />
    <ProjectReference Include="..\..\Services\CartService\Store.CartService.csproj" />
    <ProjectReference Include="..\..\Services\OrderService\Store.OrderService.csproj" />
    <ProjectReference Include="..\..\Services\AuditLogService\Store.AuditLogService.csproj" />
    <ProjectReference Include="..\..\Gateway\APIGateway\Store.GatewayService.csproj" />
  </ItemGroup>

</Project>
