<#
.SYNOPSIS
  Drops the local database of every service and recreates it from the migrations in the repository.

.DESCRIPTION
  Migrations are code: they are never deleted or regenerated by a script. This one only
  resets the data - each service's database is dropped and the service is started with
  "--migrate", which applies the committed migrations, runs the seed (catalogue, roles,
  demo accounts) and exits.

  Needs: PostgreSQL from docker compose with its port on the host
  ("docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d postgres"), the dotnet-ef
  tool ("dotnet tool install -g dotnet-ef") and the connection strings from
  appsettings.Development.json. Secrets are not needed for this step.

  The action is destructive, so it asks for confirmation; pass -Force to skip the prompt.

.PARAMETER Service
  Reset only the given services (IdentityService, ProductService, CartService,
  OrderService, AuditLogService). Default: all of them.

.EXAMPLE
  ./Scripts/Reset-Local-Databases.ps1
  ./Scripts/Reset-Local-Databases.ps1 -Service OrderService, CartService -Force
#>
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
param(
  [ValidateSet('IdentityService', 'ProductService', 'CartService', 'OrderService', 'AuditLogService')]
  [string[]]$Service = @('IdentityService', 'ProductService', 'CartService', 'OrderService', 'AuditLogService'),
  [switch]$Force,
  [string]$RootPath = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = 'Stop'

if ($Force) { $ConfirmPreference = 'None' }
if (-not $PSCmdlet.ShouldProcess(($Service -join ', '), 'Drop the local database and recreate it from the migrations')) {
  return
}

$env:ASPNETCORE_ENVIRONMENT = 'Development'

foreach ($name in $Service) {
  $project = Join-Path $RootPath "Services/$name"
  if (-not (Test-Path $project)) { throw "Project not found: $project" }

  Write-Host "[$name] Dropping database..." -ForegroundColor Yellow
  dotnet ef database drop --force --project $project
  if ($LASTEXITCODE -ne 0) { throw "[$name] dotnet ef database drop failed" }

  Write-Host "[$name] Applying migrations and seed..." -ForegroundColor Cyan
  dotnet run --project $project --no-launch-profile -- --migrate
  if ($LASTEXITCODE -ne 0) { throw "[$name] migration run failed" }

  Write-Host "[$name] Done." -ForegroundColor Green
}

Write-Host "All requested databases were recreated." -ForegroundColor Green
