version: '3.8'

# Docker Compose override for development environment
# This file extends the base docker-compose.yml with development-specific configurations

services:
  # Development overrides for PostgreSQL
  postgres:
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=store_user
      - POSTGRES_PASSWORD=StrongPassword123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh:ro
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro

  # Development overrides for Redis
  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ""

  # Development overrides for Identity Service
  identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=store_identity_db;Username=store_user;Password=StrongPassword123!;Port=5432;
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs

  # Development overrides for Product Service
  product-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=store_product_db;Username=store_user;Password=StrongPassword123!;Port=5432;
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "5002:5002"
    volumes:
      - ./logs:/app/logs

  # Development overrides for Cart Service
  cart-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=store_cart_db;Username=store_user;Password=StrongPassword123!;Port=5432;
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "5003:5003"
    volumes:
      - ./logs:/app/logs

  # Development overrides for Order Service
  order-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5004
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=store_order_db;Username=store_user;Password=StrongPassword123!;Port=5432;
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "5004:5004"
    volumes:
      - ./logs:/app/logs

  # Development overrides for Audit Service
  audit-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5005
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=store_audit_db;Username=store_user;Password=StrongPassword123!;Port=5432;
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "5005:5005"
    volumes:
      - ./logs:/app/logs

  # Development overrides for API Gateway
  gateway-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs

  # Development overrides for Frontend
  frontend:
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:5000
      - VITE_API_GATEWAY_URL=http://localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ../UI/store-app.UI/src:/app/src
      - ../UI/store-app.UI/public:/app/public

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  store-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
