/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A page of the public catalogue, filtered and sorted by the query. */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    category?: string;
                    group?: string;
                    company?: string;
                    /** @description One colour, as the shop's filter form sends it; the same as colors with a single value. */
                    color?: string;
                    order?: string;
                    price?: string;
                    sale?: string;
                    page?: number;
                    pageSize?: number;
                    materials?: string;
                    colors?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponsePagedResponse"];
                    };
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Creates a product; the body is validated before the action runs. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateProductRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One active product; 404 for an unknown or deleted id. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        /** Partial update: absent fields keep their value, the nullable ones can be cleared with null. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Removes the product from the public catalogue but keeps the row, so past orders keep a
         *     valid reference and an admin can reactivate it with an update.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The values the catalogue can be filtered by. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductsMeta"];
                    };
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every product, inactive ones included, sorted by sortBy (id, price,
         *     title, company) in sortDir (asc, desc).
         */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    category?: string;
                    group?: string;
                    company?: string;
                    /** @description One colour, as the shop's filter form sends it; the same as colors with a single value. */
                    color?: string;
                    order?: string;
                    price?: string;
                    sale?: string;
                    page?: number;
                    pageSize?: number;
                    materials?: string;
                    colors?: string;
                    sortBy?: string;
                    sortDir?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponsePagedResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What another service needs to know about a product (title, image, colours, the price the
         *     customer pays right now). Service-to-service only: callers present the internal API key.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductSnapshot"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Category: "all" | "sofas" | "chairs" | "tables" | "beds" | "mattresses" | "desks" | "tvStands" | "bookcases" | "wardrobes" | "dressers" | "nightstands" | "sideboards" | "rugs" | "outdoorFurniture" | "entrywayFurniture" | "decor" | "bathroomStorage" | "bathroomFurniture" | "bathroomMirrors" | "kitchenCabinets" | "kitchenIslands" | "gardenSets" | "kidsBeds" | "kidsDesks" | "tableLamps" | "floorLamps";
        /** @enum {string} */
        Company: "all" | "modenza" | "luxora" | "artifex" | "comfora" | "homestead";
        /** @description Body of POST /api/v1/products. Rules: `CreateProductRequestValidator`. */
        CreateProductRequest: {
            title: string;
            description: string;
            /** Format: double */
            price: number;
            /** Format: double */
            salePrice?: number | null;
            /** Format: double */
            discountPercent?: number | null;
            category: components["schemas"]["Category"];
            company: components["schemas"]["Company"];
            newArrival: boolean;
            image: string;
            colors: string[];
            groups?: string[] | null;
            /** Format: double */
            widthCm?: number | null;
            /** Format: double */
            heightCm?: number | null;
            /** Format: double */
            depthCm?: number | null;
            /** Format: double */
            weightKg?: number | null;
            materials?: string[] | null;
        };
        /**
         * Format: double
         * @description A request field that distinguishes "not sent" from "sent as null". A partial update can
         *     then clear a value (`"salePrice": null`) as well as leave it alone (property absent),
         *     which a plain nullable property cannot express - both arrive as null.
         */
        DecimalNullableOptional: number | null;
        GroupWithCategories: {
            key: string;
            name: string;
            categories: components["schemas"]["OptionItem"][];
        };
        /** @description Option of a dropdown: the key sent back in queries and the label to show. */
        OptionItem: {
            key: string;
            name: string;
        };
        ProductResponse: {
            /** Format: int32 */
            id: number;
            title: string;
            description: string;
            /** Format: double */
            price: number;
            /** Format: double */
            salePrice?: number | null;
            /** Format: double */
            discountPercent?: number | null;
            /**
             * Format: double
             * @description Price the customer pays (sale price or discounted price, else the list price).
             */
            effectivePrice: number;
            category: components["schemas"]["Category"];
            company: components["schemas"]["Company"];
            newArrival: boolean;
            image: string;
            colors: string[];
            groups: string[];
            /** Format: double */
            widthCm?: number | null;
            /** Format: double */
            heightCm?: number | null;
            /** Format: double */
            depthCm?: number | null;
            /** Format: double */
            weightKg?: number | null;
            materials: string[];
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        /** @description One page of a listing, the same shape for every resource. */
        ProductResponsePagedResponse: {
            items: components["schemas"]["ProductResponse"][];
            /**
             * Format: int32
             * @description Rows in the whole listing, not on this page.
             */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            readonly totalPages: number;
            readonly hasNextPage: boolean;
            readonly hasPreviousPage: boolean;
        };
        /**
         * @description What the catalogue tells other services about a product: enough to show a cart line and
         *     to charge the right price. Returned by `GET /api/v1/products/{id}/snapshot`; the caller
         *     stores the fields it needs instead of keeping a copy of the product.
         */
        ProductSnapshot: {
            /**
             * Format: int32
             * @description Product id
             */
            id: number;
            /** @description Display name */
            title: string;
            /** @description Image URL */
            image: string;
            /** @description Brand name as text */
            company: string;
            /** @description Colour variants the product is sold in */
            colors: string[];
            /**
             * Format: double
             * @description List price
             */
            price: number;
            /**
             * Format: double
             * @description The price a customer pays right now (sale price or discounted list price)
             */
            effectivePrice: number;
            /** @description False once the product was deleted from the catalogue */
            isActive: boolean;
            /**
             * Format: date-time
             * @description Last change in the catalogue, for callers that cache
             */
            updatedAt: string;
        };
        /**
         * @description The values the catalogue can be filtered by, for the shop's menus and the admin form.
         *     Keys use the same spelling as the product fields ("tvStands", "modenza"); "all" comes
         *     first so a menu can default to it.
         */
        ProductsMeta: {
            categories: string[];
            groups: string[];
            companies: string[];
            colors: string[];
            /** @description Groups with the categories that belong to them, for dependent dropdowns. */
            groupCategoryMap: components["schemas"]["GroupWithCategories"][];
        };
        /**
         * @description The error response as this store fills it, for the document only: the RFC 9457 members
         *     plus the trace id every problem carries and the field messages of a validation problem.
         */
        StoreProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            /** @description W3C trace id of the request, to find it in the logs. */
            traceId?: string | null;
            /** @description Messages per field of a 422 problem. */
            errors?: {
                [key: string]: string[];
            } | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Body of PUT /api/v1/products/{id}: a partial update. A property that is absent keeps the
         *     current value. Fields that can be empty use Store.BuildingBlocks.Api.Optional`1, so sending them as
         *     null clears them - that is how a promotion is taken off a product.
         *     Rules: `UpdateProductRequestValidator`.
         */
        UpdateProductRequest: {
            title?: string | null;
            description?: string | null;
            /** Format: double */
            price?: number | null;
            salePrice?: components["schemas"]["DecimalNullableOptional"];
            discountPercent?: components["schemas"]["DecimalNullableOptional"];
            category?: components["schemas"]["Category"];
            company?: components["schemas"]["Company"];
            newArrival?: boolean | null;
            image?: string | null;
            colors?: string[] | null;
            /** @description Replaces the whole list when present; an empty list removes every group. */
            groups?: string[] | null;
            widthCm?: components["schemas"]["DecimalNullableOptional"];
            heightCm?: components["schemas"]["DecimalNullableOptional"];
            depthCm?: components["schemas"]["DecimalNullableOptional"];
            weightKg?: components["schemas"]["DecimalNullableOptional"];
            /** @description Replaces the whole list when present; an empty list removes every material. */
            materials?: string[] | null;
            /** @description False hides the product from the public catalogue, true brings a deleted one back. */
            isActive?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
