/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/discount-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every code, active or not, in alphabetical order. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiscountCodeResponse"][];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** A new code; 409 when another code has the same letters. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DiscountCodeRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiscountCodeResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/discount-codes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One code; 404 when the id is unknown. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiscountCodeResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        /** Replaces a code's rules; the count of its uses stays. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DiscountCodeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiscountCodeResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        /** Deletes a code no order used; a used one is 409 and can be switched off instead. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All orders, newest first. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponsePagedResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/by-user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders of one customer, newest first; an empty page when they have none. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponsePagedResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One order; 404 when the id is unknown. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Ships a paid order or cancels one not shipped yet; a paid order that is cancelled is refunded
         *     by the saga. A move the order's status does not allow is 409; only the true administrator may
         *     change orders.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateOrderStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/admin/orders/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders and revenue per day, per week and per product over the last days days. */
        get: {
            parameters: {
                query?: {
                    days?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderStatsResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/pricing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The rules an order is priced by (delivery fee and its free-delivery threshold, first-order
         *     discount), for the cart page to preview the amounts the way the checkout will compute them,
         *     and the days an order placed now should arrive between.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricingRulesResponse"];
                    };
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/discount-codes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What a discount code takes off subtotal, for the cart to preview; a
         *     code that cannot be used (unknown, expired, used up, below its minimum) is 422 saying why.
         *     The order checks the code again when it is placed.
         */
        get: {
            parameters: {
                query?: {
                    subtotal?: number;
                };
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiscountCodeCheckResponse"];
                    };
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/from-cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Places an order from the cart. Send an Idempotency-Key header (a UUID per checkout
         *     attempt): a retry with the same key returns the order created the first time.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateOrderFromCartRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One order: the customer's own, or any order for an administrator (masked for the demo one). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/my-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The customer's orders, newest first. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponsePagedResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/has-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the customer has ordered before - the first order is discounted. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HasOrdersResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body of POST /api/v1/orders/from-cart. Rules: `CreateOrderFromCartRequestValidator`. */
        CreateOrderFromCartRequest: {
            deliveryAddress?: string | null;
            customerName: string;
            notes?: string | null;
            /** @description A discount code the customer typed; the order is refused when it cannot be used. */
            discountCode?: string | null;
            /** @description Also store the delivery address in the user profile. */
            saveAddress: boolean;
        };
        /** @description What a code takes off a subtotal, for the cart to preview before the checkout. */
        DiscountCodeCheckResponse: {
            code: string;
            kind: string;
            /** Format: double */
            value: number;
            /**
             * Format: double
             * @description The amount the code takes off the subtotal it was checked with.
             */
            discountAmount: number;
        };
        /** @description Body of POST and PUT /api/v1/admin/discount-codes. Rules: `DiscountCodeRequestValidator`. */
        DiscountCodeRequest: {
            /** @description Letters, digits and dashes; stored in upper case. */
            code: string;
            /** @description Percent or Amount. */
            kind: string;
            /**
             * Format: double
             * @description The percentage (1-100) or the amount in dollars.
             */
            value: number;
            /**
             * Format: double
             * @description The smallest subtotal the code works on; none for any order.
             */
            minimumSubtotal?: number | null;
            /** Format: date-time */
            startsAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
            /**
             * Format: int32
             * @description How many orders in total may use the code; none for no limit.
             */
            usageLimit?: number | null;
            isActive: boolean;
        };
        /** @description A discount code as the admin panel sees it. */
        DiscountCodeResponse: {
            /** Format: int32 */
            id: number;
            code: string;
            kind: string;
            /** Format: double */
            value: number;
            /** Format: double */
            minimumSubtotal?: number | null;
            /** Format: date-time */
            startsAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: int32 */
            usageLimit?: number | null;
            /**
             * Format: int32
             * @description Orders the code was applied to.
             */
            timesUsed: number;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        HasOrdersResponse: {
            hasOrders: boolean;
            /** Format: int32 */
            ordersCount: number;
        };
        OrderItemResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            productId: number;
            productTitle: string;
            productImage: string;
            /** Format: double */
            price: number;
            /** Format: int32 */
            quantity: number;
            color: string;
            company: string;
            /** Format: double */
            lineTotal: number;
        };
        OrderResponse: {
            /** Format: int32 */
            id: number;
            userId: string;
            userEmail: string;
            deliveryAddress?: string | null;
            customerName: string;
            orderItems: components["schemas"]["OrderItemResponse"][];
            /** Format: int32 */
            totalItems: number;
            /**
             * Format: double
             * @description Sum of the lines before discount and delivery.
             */
            subtotal: number;
            /** Format: double */
            discountAmount: number;
            discountReason?: string | null;
            /** @description The discount code the order was discounted by, if any. */
            discountCode?: string | null;
            /** Format: double */
            deliveryFee: number;
            /**
             * Format: double
             * @description What the customer pays.
             */
            total: number;
            status: string;
            /** @description Every status the order has been in, oldest first, with the time it changed. */
            statusHistory: components["schemas"]["OrderStatusChangeResponse"][];
            /** @description What the administrator can still do with the order: Shipped (once paid), Cancelled (until shipped). */
            nextStatuses: string[];
            /**
             * Format: date
             * @description First and last day of the delivery window promised at checkout; null for older orders.
             */
            deliveryFrom?: string | null;
            /** Format: date */
            deliveryTo?: string | null;
            /**
             * Format: date-time
             * @description When the customer must have paid by; set once the stock is reserved.
             */
            paymentDueAt?: string | null;
            /** @description Brand of the card that paid (visa, mastercard). */
            cardBrand?: string | null;
            /** @description Last four digits of that card. */
            cardLast4?: string | null;
            /** @description Why the order was cancelled: out-of-stock, payment-timed-out or cancelled-by-administrator. */
            cancellationReason?: string | null;
            /** Format: date-time */
            createdAt: string;
            notes?: string | null;
        };
        /** @description One page of a listing, the same shape for every resource. */
        OrderResponsePagedResponse: {
            items: components["schemas"]["OrderResponse"][];
            /**
             * Format: int32
             * @description Rows in the whole listing, not on this page.
             */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            readonly totalPages: number;
            readonly hasNextPage: boolean;
            readonly hasPreviousPage: boolean;
        };
        OrderStatsResponse: {
            /** Format: double */
            totalRevenue: number;
            /** Format: int32 */
            totalOrders: number;
            daily: components["schemas"]["TimeBucketStats"][];
            weekly: components["schemas"]["TimeBucketStats"][];
            topProducts: components["schemas"]["TopProductStats"][];
        };
        OrderStatusChangeResponse: {
            status: string;
            /** Format: date-time */
            changedAt: string;
        };
        /**
         * @description The rules the order service prices an order by, so the cart page can preview the amounts
         *     the same way instead of keeping its own copy of the numbers. The order itself is always
         *     priced here, at checkout.
         */
        PricingRulesResponse: {
            /**
             * Format: double
             * @description Orders with a subtotal (before the discount) at or above this amount ship for free.
             */
            freeDeliveryThreshold: number;
            /**
             * Format: double
             * @description Charged below the threshold.
             */
            deliveryFee: number;
            /**
             * Format: double
             * @description Percentage taken off the subtotal of a customer's first order.
             */
            firstOrderDiscountPercent: number;
            /**
             * Format: date
             * @description First day an order placed now should arrive on.
             */
            deliveryFrom: string;
            /**
             * Format: date
             * @description Last day an order placed now should arrive on.
             */
            deliveryTo: string;
        };
        /**
         * @description The error response as this store fills it, for the document only: the RFC 9457 members
         *     plus the trace id every problem carries and the field messages of a validation problem.
         */
        StoreProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            /** @description W3C trace id of the request, to find it in the logs. */
            traceId?: string | null;
            /** @description Messages per field of a 422 problem. */
            errors?: {
                [key: string]: string[];
            } | null;
        } & {
            [key: string]: unknown;
        };
        TimeBucketStats: {
            /** Format: date-time */
            bucketStart: string;
            /** Format: int32 */
            orders: number;
            /** Format: double */
            revenue: number;
        };
        TopProductStats: {
            /** Format: int32 */
            productId: number;
            productTitle: string;
            /** Format: int32 */
            quantity: number;
            /** Format: double */
            revenue: number;
        };
        /** @description Body of PATCH /api/v1/admin/orders/{id}/status. Rules: `UpdateOrderStatusRequestValidator`. */
        UpdateOrderStatusRequest: {
            /** @description The status to move the order to: Shipped or Cancelled. */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
