/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All orders, newest first. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponsePagedResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/by-user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders of one customer, newest first; an empty page when they have none. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponsePagedResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One order; 404 when the id is unknown. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders and revenue per day, per week and per product over the last days days. */
        get: {
            parameters: {
                query?: {
                    days?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderStatsResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/pricing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The rules an order is priced by (delivery fee and its free-delivery threshold, first-order
         *     discount), for the cart page to preview the amounts the way the checkout will compute them.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricingRulesResponse"];
                    };
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/from-cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Places an order from the cart. Send an Idempotency-Key header (a UUID per checkout
         *     attempt): a retry with the same key returns the order created the first time.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateOrderFromCartRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One order: the customer's own, or any order for an administrator (masked for the demo one). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/my-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The customer's orders, newest first. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponsePagedResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/has-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the customer has ordered before - the first order is discounted. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HasOrdersResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body of POST /api/v1/orders/from-cart. Rules: `CreateOrderFromCartRequestValidator`. */
        CreateOrderFromCartRequest: {
            deliveryAddress?: string | null;
            customerName: string;
            notes?: string | null;
            /** @description Also store the delivery address in the user profile. */
            saveAddress: boolean;
        };
        HasOrdersResponse: {
            hasOrders: boolean;
            /** Format: int32 */
            ordersCount: number;
        };
        OrderItemResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            productId: number;
            productTitle: string;
            productImage: string;
            /** Format: double */
            price: number;
            /** Format: int32 */
            quantity: number;
            color: string;
            company: string;
            /** Format: double */
            lineTotal: number;
        };
        OrderResponse: {
            /** Format: int32 */
            id: number;
            userId: string;
            userEmail: string;
            deliveryAddress?: string | null;
            customerName: string;
            orderItems: components["schemas"]["OrderItemResponse"][];
            /** Format: int32 */
            totalItems: number;
            /**
             * Format: double
             * @description Sum of the lines before discount and delivery.
             */
            subtotal: number;
            /** Format: double */
            discountAmount: number;
            discountReason?: string | null;
            /** Format: double */
            deliveryFee: number;
            /**
             * Format: double
             * @description What the customer pays.
             */
            total: number;
            status: string;
            /** Format: date-time */
            createdAt: string;
            notes?: string | null;
        };
        /** @description One page of a listing, the same shape for every resource. */
        OrderResponsePagedResponse: {
            items: components["schemas"]["OrderResponse"][];
            /**
             * Format: int32
             * @description Rows in the whole listing, not on this page.
             */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            readonly totalPages: number;
            readonly hasNextPage: boolean;
            readonly hasPreviousPage: boolean;
        };
        OrderStatsResponse: {
            /** Format: double */
            totalRevenue: number;
            /** Format: int32 */
            totalOrders: number;
            daily: components["schemas"]["TimeBucketStats"][];
            weekly: components["schemas"]["TimeBucketStats"][];
            topProducts: components["schemas"]["TopProductStats"][];
        };
        /**
         * @description The rules the order service prices an order by, so the cart page can preview the amounts
         *     the same way instead of keeping its own copy of the numbers. The order itself is always
         *     priced here, at checkout.
         */
        PricingRulesResponse: {
            /**
             * Format: double
             * @description Orders with a subtotal (before the discount) at or above this amount ship for free.
             */
            freeDeliveryThreshold: number;
            /**
             * Format: double
             * @description Charged below the threshold.
             */
            deliveryFee: number;
            /**
             * Format: double
             * @description Percentage taken off the subtotal of a customer's first order.
             */
            firstOrderDiscountPercent: number;
        };
        /**
         * @description The error response as this store fills it, for the document only: the RFC 9457 members
         *     plus the trace id every problem carries and the field messages of a validation problem.
         */
        StoreProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            /** @description W3C trace id of the request, to find it in the logs. */
            traceId?: string | null;
            /** @description Messages per field of a 422 problem. */
            errors?: {
                [key: string]: string[];
            } | null;
        } & {
            [key: string]: unknown;
        };
        TimeBucketStats: {
            /** Format: date-time */
            bucketStart: string;
            /** Format: int32 */
            orders: number;
            /** Format: double */
            revenue: number;
        };
        TopProductStats: {
            /** Format: int32 */
            productId: number;
            productTitle: string;
            /** Format: int32 */
            quantity: number;
            /** Format: double */
            revenue: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
