/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/payments/internal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Opens the payment of an order; the order service calls it with the Idempotency-Key
         *     "order-{id}". Opening it again returns the same payment (200 instead of 201); the same order
         *     with another amount or customer is 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreatePaymentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentSnapshot"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentSnapshot"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A payment of the signed-in customer; 403 for another customer's. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pays with a card. The answer is the payment after the charge: succeeded, waiting for the
         *     3-D Secure check (requiresAction), or still open with the reason the card was refused. A
         *     payment already paid, cancelled or waiting for its check is 409.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ConfirmPaymentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{id}/authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The customer's answer in the 3-D Secure window: approved pays, rejected refuses the card. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AuthenticatePaymentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body of POST /api/v1/payments/{id}/authenticate: the customer's answer in the 3-D Secure window. */
        AuthenticatePaymentRequest: {
            approve: boolean;
        };
        /**
         * @description Body of POST /api/v1/payments/{id}/confirm: the card, typed by the customer. Only the test
         *     cards are taken (see `TestCards`); rules: `ConfirmPaymentRequestValidator`.
         */
        ConfirmPaymentRequest: {
            /** @description Digits, spaces and dashes allowed. */
            cardNumber: string;
            /**
             * Format: int32
             * @description 1-12.
             */
            expMonth: number;
            /**
             * Format: int32
             * @description Four digits.
             */
            expYear: number;
            cvc: string;
        };
        /**
         * @description Body of `POST /api/v1/payments/internal`, with which the order service opens the payment
         *     of an order (an internal call, with the key "order-{id}" in the Idempotency-Key header). One
         *     payment per order: asking again returns the payment made the first time.
         */
        CreatePaymentRequest: {
            /**
             * Format: int32
             * @description The order to be paid
             */
            orderId: number;
            /** @description The customer; only they may pay it */
            userId: string;
            /**
             * Format: double
             * @description What the order costs
             */
            amount: number;
            /** @description ISO code, lowercase ("usd") */
            currency: string;
        };
        /** @description A payment as its customer sees it. */
        PaymentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            orderId: number;
            /** Format: double */
            amount: number;
            /** @description ISO code, lowercase. */
            currency: string;
            status: components["schemas"]["PaymentStatus"];
            /** @description Brand of the card that paid, or of the one waiting for its 3-D Secure check, or of the one refused. */
            cardBrand?: string | null;
            cardLast4?: string | null;
            /** @description Why the last card was refused: card-declined, insufficient-funds or authentication-failed. */
            declineReason?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description What the payment service tells the order service about a payment. */
        PaymentSnapshot: {
            /**
             * Format: uuid
             * @description Id of the payment; the browser confirms it with a card at the payment service
             */
            id: string;
            /**
             * Format: int32
             * @description The order it pays for
             */
            orderId: number;
            /**
             * Format: double
             * @description Amount to take
             */
            amount: number;
            /** @description ISO code, lowercase */
            currency: string;
            /** @description requiresPaymentMethod, requiresAction, succeeded, cancelled or refunded */
            status: string;
            /**
             * Format: date-time
             * @description When it was opened (UTC)
             */
            createdAt: string;
        };
        /**
         * @description Stored by name; the API writes them in camelCase.
         * @enum {string}
         */
        PaymentStatus: "requiresPaymentMethod" | "requiresAction" | "succeeded" | "cancelled" | "refunded";
        /**
         * @description The error response as this store fills it, for the document only: the RFC 9457 members
         *     plus the trace id every problem carries and the field messages of a validation problem.
         */
        StoreProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            /** @description W3C trace id of the request, to find it in the logs. */
            traceId?: string | null;
            /** @description Messages per field of a 422 problem. */
            errors?: {
                [key: string]: string[];
            } | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
