/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/reviews/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews by state: queue (default: new and reported, oldest first), pending, reported, published, rejected or all. */
        get: {
            parameters: {
                query?: {
                    /** @description Which reviews: the queue (waiting for a decision - new or reported) unless another set is asked for. */
                    status?: components["schemas"]["ReviewQueueFilter"];
                    productId?: number;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminReviewResponsePagedResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/admin/moderate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approves or rejects (with a reason the author sees) one review or many at once. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ModerateReviewsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModerationResult"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published reviews of a product, filtered by stars or verified purchase, newest first unless sorted otherwise. */
        get: {
            parameters: {
                query?: {
                    productId?: number;
                    /** @description Only the reviews with this many stars (1-5). */
                    rating?: number;
                    /** @description true: only reviews by customers who bought the product. */
                    verified?: boolean;
                    /** @description Newest first unless another order is asked for. */
                    sort?: components["schemas"]["ReviewSort"];
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewResponsePagedResponse"];
                    };
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Writes a review; it waits for moderation. 403 for a product not in a paid order, 409 for a
         *     second review of it (a rejected one may be written again), 422 over three reviews a day or
         *     for text the automatic checks refuse.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateReviewRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/products/{productId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The rating of a product: average, count and reviews per number of stars. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewSummaryResponse"];
                    };
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The ratings of many products at once (comma-separated ids, at most 100; others are ignored). */
        get: {
            parameters: {
                query?: {
                    ids?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewSummaryResponse"][];
                    };
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The shop's rating: the average and the count of every published review, whatever the product. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShopReviewStatsResponse"];
                    };
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/products/{productId}/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the signed-in customer may review the product, and their review of it in any state. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MyProductReviewResponse"];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in customer's reviews in any state (on a demo account: the ones of this sign-in session). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewResponse"][];
                    };
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reports a published review; from a customer's account it is hidden until the administrator looks at it. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReportReviewRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No valid access token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The signed-in user may not do this */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error, as an RFC 9457 problem (application/problem+json) */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["StoreProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A review in the moderation queue. */
        AdminReviewResponse: {
            /** Format: uuid */
            id: string;
            /**
             * Format: int32
             * @description 0 for a seeded review whose product has not been found in the catalogue yet.
             */
            productId: number;
            productSlug?: string | null;
            userId?: string | null;
            authorName: string;
            /** Format: int32 */
            rating: number;
            title?: string | null;
            body: string;
            status: components["schemas"]["ReviewStatus"];
            reported: boolean;
            /** Format: int32 */
            reportCount: number;
            /** @description The reasons given with the reports, newest first. */
            reportReasons: string[];
            rejectionReason?: string | null;
            source: components["schemas"]["ReviewSource"];
            verifiedPurchase: boolean;
            /** @description Written from a shared demo account; deleted at Store.ReviewService.DTOs.AdminReviewResponse.ExpiresAt. */
            demo: boolean;
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            moderatedAt?: string | null;
            /** @description The administrator who approved or rejected it; null when the model published it. */
            moderatedBy?: string | null;
            modelVerdict?: components["schemas"]["ModelVerdict"];
            /** @description The model's reason; hidden from the demo administrator with the text it is about. */
            modelReason?: string | null;
        };
        /** @description One page of a listing, the same shape for every resource. */
        AdminReviewResponsePagedResponse: {
            items: components["schemas"]["AdminReviewResponse"][];
            /**
             * Format: int32
             * @description Rows in the whole listing, not on this page.
             */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            readonly totalPages: number;
            readonly hasNextPage: boolean;
            readonly hasPreviousPage: boolean;
        };
        /** @description Body of POST /api/v1/reviews. Rules: `CreateReviewRequestValidator` and Store.ReviewService.Services.ReviewContentRules. */
        CreateReviewRequest: {
            /** Format: int32 */
            productId: number;
            /**
             * Format: int32
             * @description 1 to 5 stars.
             */
            rating: number;
            /** @description Optional, up to 80 characters. */
            title?: string | null;
            /** @description 20 to 1000 characters. */
            body: string;
        };
        /**
         * @description Stored by name. The model's reading of a new review (ADR 019).
         * @enum {string}
         */
        ModelVerdict: "clean" | "doubtful";
        /** @description Body of POST /api/v1/reviews/admin/moderate: one decision for one or many reviews. */
        ModerateReviewsRequest: {
            /** @description 1 to 100 reviews. */
            ids: string[];
            decision: components["schemas"]["ModerationDecision"];
            /** @description Required to reject, up to 300 characters; the review's author sees it. */
            reason?: string | null;
        };
        /**
         * @description Stored nowhere; serialised by name.
         * @enum {string}
         */
        ModerationDecision: "approve" | "reject";
        /** @description What a moderation request changed. */
        ModerationResult: {
            /**
             * Format: int32
             * @description Reviews the decision was applied to.
             */
            moderated: number;
            /** @description Ids that were not found (deleted demo reviews, for instance). */
            notFound: string[];
        };
        /** @description Whether the signed-in customer may review a product, and their review of it if they wrote one. */
        MyProductReviewResponse: {
            /** Format: int32 */
            productId: number;
            canReview: boolean;
            reason?: components["schemas"]["ReviewBlockReason"];
            review?: components["schemas"]["ReviewResponse"];
        };
        /** @description Body of POST /api/v1/reviews/{id}/report. */
        ReportReviewRequest: {
            /** @description What is wrong with it, optional, up to 300 characters. */
            reason?: string | null;
        };
        /**
         * @description Why a signed-in customer may not review a product.
         * @enum {string}
         */
        ReviewBlockReason: "notPurchased" | "alreadyReviewed" | "dailyLimit" | "signInAgain";
        /**
         * @description The sets of reviews the moderation queue shows.
         * @enum {string}
         */
        ReviewQueueFilter: "queue" | "pending" | "reported" | "published" | "rejected" | "all";
        /** @description A review as the shop prints it. */
        ReviewResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            productId: number;
            /** @description A first name and an initial. */
            authorName: string;
            /** Format: int32 */
            rating: number;
            title?: string | null;
            body: string;
            verifiedPurchase: boolean;
            status: components["schemas"]["ReviewStatus"];
            /** @description Why it was not published; only in its author's own view. */
            rejectionReason?: string | null;
            /** @description True in its author's view while a report keeps it hidden from the others. */
            reported: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description One page of a listing, the same shape for every resource. */
        ReviewResponsePagedResponse: {
            items: components["schemas"]["ReviewResponse"][];
            /**
             * Format: int32
             * @description Rows in the whole listing, not on this page.
             */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            readonly totalPages: number;
            readonly hasNextPage: boolean;
            readonly hasPreviousPage: boolean;
        };
        /**
         * @description The orders the published reviews of a product are listed in.
         * @enum {string}
         */
        ReviewSort: "newest" | "oldest" | "highest" | "lowest";
        /**
         * @description Stored by name; tells seeded reviews from customers' ones in the admin panel.
         * @enum {string}
         */
        ReviewSource: "seed" | "customer";
        /**
         * @description Stored by name.
         * @enum {string}
         */
        ReviewStatus: "pending" | "published" | "rejected";
        /** @description What the published reviews of a product add up to. */
        ReviewSummaryResponse: {
            /** Format: int32 */
            productId: number;
            /**
             * Format: double
             * @description Average of the published ratings, two decimals; 0 without reviews.
             */
            averageRating: number;
            /** Format: int32 */
            reviewCount: number;
            /** @description Reviews per number of stars, "1" to "5", each key present. */
            distribution: {
                [key: string]: number;
            };
        };
        /** @description What the published reviews of the whole catalogue add up to, for the shop's own pages. */
        ShopReviewStatsResponse: {
            /**
             * Format: double
             * @description Average of the published ratings, two decimals; 0 without reviews.
             */
            averageRating: number;
            /** Format: int32 */
            reviewCount: number;
        };
        /**
         * @description The error response as this store fills it, for the document only: the RFC 9457 members
         *     plus the trace id every problem carries and the field messages of a validation problem.
         */
        StoreProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
            /** @description W3C trace id of the request, to find it in the logs. */
            traceId?: string | null;
            /** @description Messages per field of a 422 problem. */
            errors?: {
                [key: string]: string[];
            } | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
